import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Cpu, Layers, Users, Globe, TrendingUp, BookOpen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export const Route = createFileRoute("/")({
  component: HomePage,
});

const stats = [
  { value: "5,000+", label: "Tons of E-Waste Recovered" },
  { value: "50+", label: "Partner Organizations" },
  { value: "12", label: "Cities Served" },
  { value: "$2M+", label: "In Recovered Material Value" },
];

const whyItems = [
  {
    icon: Globe,
    title: "Environmental Impact",
    text: "E-waste is the fastest-growing waste stream globally. Every ton we recover keeps toxic materials out of landfills.",
  },
  {
    icon: TrendingUp,
    title: "Economic Opportunity",
    text: "Urban mining creates skilled green jobs and keeps material value circulating in local communities.",
  },
  {
    icon: BookOpen,
    title: "Community Education",
    text: "We empower residents and businesses with the knowledge to make sustainable, lasting choices.",
  },
];

const featuredPrograms = [
  {
    icon: Cpu,
    title: "E-Waste Recovery",
    description:
      "Collecting and responsibly processing electronic waste to recover valuable materials and keep toxins out of landfills.",
    badge: "Active",
  },
  {
    icon: Layers,
    title: "Precious Metal Reclamation",
    description:
      "Extracting gold, silver, copper, and rare earth elements from discarded electronics using sustainable processes.",
    badge: "Active",
  },
  {
    icon: Users,
    title: "Community Drop-off Centers",
    description:
      "Convenient, accessible collection points across the city where residents can drop off recyclable materials.",
    badge: "Expanding",
  },
];

function HomePage() {
  return (
    <div className="flex flex-col">
      {/* Hero */}
      <section className="bg-primary text-primary-foreground py-24 px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-4xl text-center">
          <Badge variant="secondary" className="mb-6">
            Sustainability · Circularity · Community
          </Badge>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight mb-6 leading-tight">
            Recovering Value.
            <br />
            Building Futures.
          </h1>
          <p className="text-lg sm:text-xl text-primary-foreground/80 max-w-2xl mx-auto mb-10">
            The Urban Mining Initiative transforms discarded electronics and urban waste into valuable
            resources — creating jobs, protecting the environment, and building a circular economy for all.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button asChild size="lg" variant="secondary">
              <Link to="/programs">
                Explore Our Programs <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
            <Button
              asChild
              size="lg"
              variant="outline"
              className="border-primary-foreground/40 text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"
            >
              <Link to="/get-involved">Get Involved</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Stats bar */}
      <section className="py-14 bg-muted/50 border-b">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            {stats.map((stat) => (
              <div key={stat.label}>
                <div className="text-3xl sm:text-4xl font-bold text-primary">{stat.value}</div>
                <div className="text-sm text-muted-foreground mt-1">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* What is Urban Mining */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-7xl">
          <div className="grid md:grid-cols-2 gap-12 items-center">
            <div>
              <Badge className="mb-4">Our Mission</Badge>
              <h2 className="text-3xl sm:text-4xl font-bold mb-6">What Is Urban Mining?</h2>
              <p className="text-muted-foreground text-lg mb-4 leading-relaxed">
                Urban mining is the process of reclaiming compounds and elements from products, buildings,
                and waste generated by cities. Every discarded smartphone, laptop, and appliance contains
                recoverable gold, silver, copper, and rare earth minerals.
              </p>
              <p className="text-muted-foreground mb-8 leading-relaxed">
                The Urban Mining Initiative brings together technology, community engagement, and sustainable
                practices to recover these materials — diverting waste from landfills and returning value
                to the community.
              </p>
              <Button asChild>
                <Link to="/about">
                  Learn About Us <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
            </div>
            <div className="bg-muted rounded-2xl p-8 flex flex-col gap-6">
              {whyItems.map((item) => (
                <div key={item.title} className="flex gap-4">
                  <div className="flex-shrink-0 w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                    <item.icon className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <div className="font-semibold text-sm mb-1">{item.title}</div>
                    <div className="text-muted-foreground text-sm leading-relaxed">{item.text}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Programs preview */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-muted/30">
        <div className="mx-auto max-w-7xl">
          <div className="text-center mb-12">
            <Badge className="mb-4">What We Do</Badge>
            <h2 className="text-3xl sm:text-4xl font-bold mb-4">Our Programs</h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              From community drop-offs to corporate partnerships, our programs make sustainable resource
              recovery accessible to everyone.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {featuredPrograms.map((program) => (
              <Card key={program.title} className="hover:shadow-md transition-shadow">
                <CardHeader>
                  <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-3">
                    <program.icon className="h-6 w-6 text-primary" />
                  </div>
                  <div className="flex items-center justify-between gap-2">
                    <CardTitle className="text-lg">{program.title}</CardTitle>
                    <Badge variant="outline" className="text-xs flex-shrink-0">
                      {program.badge}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent>
                  <CardDescription className="leading-relaxed">{program.description}</CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
          <div className="text-center mt-10">
            <Button asChild variant="outline" size="lg">
              <Link to="/programs">
                View All Programs <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
          </div>
        </div>
      </section>

      {/* CTA banner */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-primary text-primary-foreground">
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="text-3xl sm:text-4xl font-bold mb-4">Ready to Make a Difference?</h2>
          <p className="text-primary-foreground/80 text-lg mb-8 leading-relaxed">
            Join hundreds of individuals, businesses, and organizations working together to build a more
            sustainable urban future.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button asChild size="lg" variant="secondary">
              <Link to="/get-involved">Get Involved Today</Link>
            </Button>
            <Button
              asChild
              size="lg"
              variant="outline"
              className="border-primary-foreground/40 text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"
            >
              <Link to="/contact">Contact Us</Link>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
}
